services:
  runner:
    build:
      context: ./backend/python/runner
    image: telegram-ai-agent
    container_name: agent-runner
    entrypoint: ["true"]
    env_file:
      - ./backend/python/.env
    restart: on-failure

  consumer:
    build:
      context: ./backend/python/consumer
    container_name: agent-consumer
    depends_on:
      - runner
    env_file:
      - ./backend/python/.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure

  server:
    build:
      context: ./backend/javascript
    container_name: backend-server
    env_file:
      - ./backend/javascript/.env
    expose:
      - "5000"
    restart: on-failure

  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nginx
    depends_on:
      - server
    ports:
      - "80:80"
    restart: on-failure
