services:
  runner:
    build:
      context: ./backend/python/runner
    image: telegram-ai-agent
    container_name: agent-runner
    entrypoint: ["true"]
    env_file:
      - ./backend/python/.env
    restart: on-failure

  consumer:
    build:
      context: ./backend/python/consumer
    container_name: agent-consumer
    depends_on:
      - runner
    env_file:
      - ./backend/python/.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure

  server:
    build:
      context: ./backend/javascript
    container_name: backend-server
    env_file:
      - ./backend/javascript/.env
    expose:
      - 5000
    restart: on-failure

  client:
    build:
      context: ./frontend
    container_name: frontend-client
    depends_on:
      - server
    restart: on-failure

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - server
      - client
    ports:
      - 80:80
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: on-failure
