services:
  runner:
    build:
      context: ./backend/python/runner
    image: docker.io/vladvez/telegram-ai-agent:${TAG}
    entrypoint: ["true"]
    env_file:
      - ./env/python.env
    restart: on-failure

  consumer:
    build:
      context: ./backend/python/consumer
    image: docker.io/vladvez/agent-consumer:${TAG}
    depends_on:
      - runner
    env_file:
      - ./env/python.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure

  server:
    build:
      context: ./backend/javascript
    image: docker.io/vladvez/backend-server:${TAG}
    env_file:
      - ./env/javascript.env
    expose:
      - "5000"
    restart: on-failure

  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: docker.io/vladvez/nginx-fe:${TAG}
    depends_on:
      - server
    ports:
      - "80:80"
    restart: on-failure
